url: localhost
baseurl: 

# Site settings
title: CS Undergraduate Student Board
email: usb@cs.purdue.edu
description: "The Computer Science Undergraduate Student Board (USB) is awesome."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: dd6b27
  secondary: a94500  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kirby Kohlmorgen
  pic: kirby
  position: President

- name: Andrew Shildmyer
  pic: andrew
  position: Vice President

- name: Ivan Zhang
  pic: ivan
  position: Treasurer

- name: Emma Wynne
  pic: emma
  position: Science Fair

- name: Scott Opell
  pic: scott
  position: Server Project

- name: Levi Starrett
  pic: levi
  position: CS 190

- name: Ben Aldefer
  pic: ben
  position: BoilerMake

- name: Evan Walsh
  pic: evan
  position: CS 190

- name: Mason Everet
  pic: mason
  position: Hardware Lab

- name: Spencer Brown
  pic: spencer
  position: CS 190

- name: Rhys Howell
  pic: rhys
  position: Science Fair

- name: Bryan Duffy
  pic: duffy
  position: PM Course

- name: Jay Hankins
  pic: jay
  position: Design

- name: Matt Ess
  pic: matt
  position: Help Room

- name: Shane DeWael
  pic: shane
  position: CPP Mixer

- name: Caitlin Kennedy
  pic: caitlin
  position: USB Labs

- name: Marty Von Kausas
  pic: marty
  position: Special Projects

- name: Adam Loeb
  pic: adam
  position: Server Project

# Postal address (add as many lines as necessary)
address:
  - line: 305 N. University St.
  - line: West Lafayette, IN 47907

# Build settings
markdown: kramdown
permalink: pretty
