# url: http://web.ics.purdue.edu/~csusb/
url: localhost
# baseurl: http://web.ics.purdue.edu/~csusb/
baseurl: 

# Site settings
title: CS Undergraduate Student Board
email: usb@cs.purdue.edu
description: "The Computer Science Undergraduate Student Board (USB) is awesome."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: dd6b27
  secondary: a94500  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kirby Kohlmorgen
  pic: kirby
  position: President

- name: Andrew Shildmyer
  pic: andrew
  position: Vice President

- name: Scott Opell
  pic: scott
  position: Treasurer

- name: Clyde Byrd
  pic: clyde
  position: Interview Workshop

- name: Emma Wynne
  pic: emma
  position: Science Fair

- name: Ivan Zhang
  pic: ivan
  position: Help Room

- name: Levi Starrett
  pic: levi
  position: CS 190

- name: Bryan Duffy
  pic: duffy
  position: PM Course

- name: Evan Walsh
  pic: evan
  position: CS 190

- name: Mason Everet
  pic: mason
  position: Hardware Lab

- name: Rhys Howell
  pic: rhys
  position: Science Fair

- name: Richard Wei
  pic: richard
  position: Design

- name: Spencer Brown
  pic: spencer
  position: BoilerMake

- name: Ben Aldefer
  pic: ben
  position: BoilerMake

# Postal address (add as many lines as necessary)
address:
  - line: 305 N. University St.
  - line: West Lafayette, IN 47907

# Build settings
markdown: kramdown
permalink: pretty
