url: localhost
baseurl:

# Site settings
title: CS Undergraduate Student Board
email: usb@cs.purdue.edu
description: "The Computer Science Undergraduate Student Board (USB) is awesome."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: dd6b27
  secondary: a94500
  secondary-dark: 333

# Team names, titles and social links
people:
# Seniors
- name: Ben Aldefer
  pic: ben
  position: Former President

- name: Bryan Duffy
  pic: duffy
  position: Former Treasurer

- name: Evan Walsh
  pic: evan
  position: CS 190

- name: Mason Everet
  pic: mason
  position: Hardware Lab

- name: Rhys Howell
  pic: rhys
  position: Science Fair

- name: Spencer Brown
  pic: spencer
  position: CS 190

# Juniors
- name: Adam Loeb
  pic: adam
  position: Server Project

- name: Caitlin Kennedy
  pic: caitlin
  position: USB Labs

- name: Jay Hankins
  pic: jay
  position: President

- name: Marty Von Kausas
  pic: marty
  position: Former Vice President

- name: Matt Ess
  pic: matt
  position: Help Room

- name: Shane DeWael
  pic: shane
  position: CPP Mixer

# Sophomores

- name: Ahad Sagheer
  pic: ahad
  position: Help Room

- name: Cole Johnson
  pic: cole
  position: Vice President

- name: Emmy Zhang
  pic: emmy
  position: Shadow Day

- name: Ian Renfro
  pic: ian
  position: Help Room

- name: Kameron Lutes
  pic: kameron
  position: Shadow Day

- name: Puja Mittal
  pic: puja
  position: Kanban Challenge

# Freshman

- name: Amol Jha
  pic: amol
  position:

- name: Ian Zanger
  pic: ianz
  position: Secretary

- name: Ivy Chenyao
  pic: ivy
  position: Design Workshops

- name: Nirali Rai
  pic: nirali
  position: Treasurer

- name: Rohan Gupta
  pic: rohan
  position:

- name: Zach Johnson
  pic: zach
  position: Design Workshops

# Postal address (add as many lines as necessary)
address:
  - line: 305 N. University St.
  - line: West Lafayette, IN 47907

# Build settings
markdown: kramdown
permalink: pretty
